### ISSUE TITLE
Cannot create constant with name 'start'

### ISSUE THREAD

**Issue by istudyatuni** [rodrimati1992/const_format_crates#44]
Sample

```rs
use const_format::formatcp;

const NAME: &str = "John";
const start: &str = formatcp!("{NAME}, age {}!", compute_age(NAME));

const fn compute_age(s: &str) -> usize { s.len() * 6 }

fn main() {
    println!("Hello, {}", start);
}
```

Error:

```
error[E0530]: let bindings cannot shadow constants
 --> src/main.rs:6:21
  |
6 | const start: &str = formatcp!("{NAME}, age {}!", compute_age(NAME));
  | --------------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^-
  | |                   |
  | |                   cannot be named the same as a constant
  | the constant `start` is defined here
  |
  = note: this error originates in the macro `__write_pvariant` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by istudyatuni** [comment]
Hey, why wontfix? Just curious

**Comment by jquesada2016** [comment]
I'm pretty sure this is because it messes with the `start` entry point of programs.

**Comment by istudyatuni** [comment]
Did you mean at the assembly level?

**Comment by istudyatuni** [comment]
```rs
const _start: &str = formatcp!("{NAME}, age {}!", compute_age(NAME));
const start: &str = _start;
```

**Comment by istudyatuni** [comment]
Works on 0.2.32. I don't understand what's changed at all.
